export interface BondFDItem {
  id: string;
  name: string;
  issuer: string;
  isin: string;
  category: 'Government Bond' | 'Secured NCD' | 'Corporate FD' | 'Tax-Free Bond' | 'US Treasury' | 'US Corporate Bond' | 'High Yield Note' | 'Treasury Bill' | 'State Development Loan' | 'Sovereign Gold Bond';
  market: 'Indian' | 'US';
  currency: '₹' | '$';
  creditRating: 'AAA' | 'AA' | 'A' | 'BBB' | 'BB' | 'SOVEREIGN';
  agencyRating: string; // e.g. CRISIL AAA, ICRA AA+, CARE A, S&P BBB, Sovereign (Govt of India)
  couponRatePct: number;
  ytmPct: number;
  tradedPrice: number;
  faceValue: number;
  exchange: string; // e.g. BSE Listed, NSE Listed, BSE & NSE, FINRA / NYSE, CCIL NDS-OM
  maturityDate: string;
  tenorYears: number;
  payoutFrequency: string; // e.g. Monthly, Annual, Cumulative, Semi-Annual, Zero-Coupon
  minInvestment: number;
  taxStatus: string;
  isSeniorSecured: boolean;
  summary: string;
  cleanPrice?: number;
  accruedInterest?: number;
  dirtyPrice?: number;
  benchmarkSpreadBps?: number;
  isSovereign?: boolean;
  dayCountConvention?: string;
  dailyTurnoverCr?: number;
  liquidityTag?: 'Highly Liquid' | 'Moderate' | 'Illiquid';
  daysSinceLastCoupon?: number;
  modifiedDurationYears?: number;
  macaulayDurationYears?: number;
  convexity?: number;
  subCategory?: 'G-Sec' | 'T-Bill' | 'SDL' | 'PSU Tax-Free' | 'Corporate NCD' | 'SGB' | 'Corporate FD';
}

export const INDIAN_BONDS_CATALOG: BondFDItem[] = [
  // 1. CENTRAL GOVERNMENT SECURITIES (G-SECS - RBI BENCHMARKS)
  {
    id: 'bond-gsec-718-2033',
    name: '7.18% GS 2033 Benchmark G-Sec',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020230085',
    category: 'Government Bond',
    subCategory: 'G-Sec',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 7.18,
    ytmPct: 7.14,
    tradedPrice: 100.25,
    cleanPrice: 100.25,
    accruedInterest: 0.72,
    dirtyPrice: 100.97,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (CCIL NDS-OM)',
    maturityDate: '14 August 2033',
    tenorYears: 7,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 0,
    dailyTurnoverCr: 3500,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 73,
    modifiedDurationYears: 6.82,
    macaulayDurationYears: 7.06,
    convexity: 56.4,
    summary: 'Flagship 10-Year Benchmark Sovereign Government Bond backed 100% by RBI. Daily NDS-OM turnover > ₹3,500 Cr.'
  },
  {
    id: 'bond-gsec-710-2034',
    name: '7.10% GS 2034 Benchmark G-Sec',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020240019',
    category: 'Government Bond',
    subCategory: 'G-Sec',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 7.10,
    ytmPct: 7.12,
    tradedPrice: 99.85,
    cleanPrice: 99.85,
    accruedInterest: 0.58,
    dirtyPrice: 100.43,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (CCIL NDS-OM)',
    maturityDate: '08 April 2034',
    tenorYears: 8,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -2,
    dailyTurnoverCr: 4200,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 60,
    modifiedDurationYears: 6.94,
    macaulayDurationYears: 7.18,
    convexity: 58.1,
    summary: 'New 10-Year Benchmark Sovereign G-Sec trading at par with deepest institutional liquidity on CCIL NDS-OM.'
  },
  {
    id: 'bond-gsec-726-2032',
    name: '7.26% GS 2032 Sovereign G-Sec',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020220037',
    category: 'Government Bond',
    subCategory: 'G-Sec',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 7.26,
    ytmPct: 7.15,
    tradedPrice: 100.60,
    cleanPrice: 100.60,
    accruedInterest: 0.81,
    dirtyPrice: 101.41,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (CCIL NDS-OM)',
    maturityDate: '22 August 2032',
    tenorYears: 6,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 1,
    dailyTurnoverCr: 1850,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 82,
    modifiedDurationYears: 5.85,
    macaulayDurationYears: 6.06,
    convexity: 43.2,
    summary: 'Active sovereign benchmark offering strong secondary turnover and attractive coupon carry.'
  },
  {
    id: 'bond-gsec-702-2029',
    name: '7.02% GS 2029 5-Year Sovereign G-Sec',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020240027',
    category: 'Government Bond',
    subCategory: 'G-Sec',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 7.02,
    ytmPct: 7.02,
    tradedPrice: 100.10,
    cleanPrice: 100.10,
    accruedInterest: 0.45,
    dirtyPrice: 100.55,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (CCIL NDS-OM)',
    maturityDate: '12 May 2029',
    tenorYears: 3,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -12,
    dailyTurnoverCr: 2100,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 47,
    modifiedDurationYears: 4.12,
    macaulayDurationYears: 4.26,
    convexity: 21.8,
    summary: 'Medium-tenor 5-Year Sovereign benchmark ideal for corporate treasury ALM and duration matching.'
  },
  {
    id: 'bond-gsec-695-2026',
    name: '6.95% GS 2026 2-Year Sovereign G-Sec',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020240035',
    category: 'Government Bond',
    subCategory: 'G-Sec',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 6.95,
    ytmPct: 6.95,
    tradedPrice: 100.05,
    cleanPrice: 100.05,
    accruedInterest: 0.35,
    dirtyPrice: 100.40,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (CCIL NDS-OM)',
    maturityDate: '15 June 2026',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -19,
    dailyTurnoverCr: 1400,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 37,
    modifiedDurationYears: 1.82,
    macaulayDurationYears: 1.88,
    convexity: 4.2,
    summary: 'Short-duration sovereign paper with minimal interest rate sensitivity and risk-free return.'
  },
  {
    id: 'bond-gsec-730-2053',
    name: '7.30% GS 2053 30-Year Long Sovereign',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020230093',
    category: 'Government Bond',
    subCategory: 'G-Sec',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 7.30,
    ytmPct: 7.35,
    tradedPrice: 99.40,
    cleanPrice: 99.40,
    accruedInterest: 0.65,
    dirtyPrice: 100.05,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (CCIL NDS-OM)',
    maturityDate: '18 September 2053',
    tenorYears: 27,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 21,
    dailyTurnoverCr: 950,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 65,
    modifiedDurationYears: 14.10,
    macaulayDurationYears: 14.61,
    convexity: 285.0,
    summary: 'Ultra long-duration 30-year sovereign paper heavily allocated by pension funds and insurance companies.'
  },

  // 2. TREASURY BILLS (T-BILLS - MONEY MARKET ZERO COUPONS)
  {
    id: 'tbill-91d-2026',
    name: '91-Day Government Treasury Bill',
    issuer: 'Government of India (GOI / RBI)',
    isin: 'IN002024X012',
    category: 'Treasury Bill',
    subCategory: 'T-Bill',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (100% RBI Guarantee)',
    couponRatePct: 0.00,
    ytmPct: 6.75,
    tradedPrice: 98.34,
    cleanPrice: 98.34,
    accruedInterest: 0.00,
    dirtyPrice: 98.34,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & Wholesale Debt',
    maturityDate: '24 December 2026',
    tenorYears: 0.25,
    payoutFrequency: 'Zero-Coupon',
    minInvestment: 25000,
    taxStatus: 'STCG as per income tax slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -39,
    dailyTurnoverCr: 2800,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 0,
    modifiedDurationYears: 0.25,
    macaulayDurationYears: 0.25,
    convexity: 0.06,
    summary: 'Zero-coupon sovereign money market bill issued at discount (₹98.34) and redeemed at ₹100 face value.'
  },
  {
    id: 'tbill-182d-2027',
    name: '182-Day Government Treasury Bill',
    issuer: 'Government of India (GOI / RBI)',
    isin: 'IN002024Y024',
    category: 'Treasury Bill',
    subCategory: 'T-Bill',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (100% RBI Guarantee)',
    couponRatePct: 0.00,
    ytmPct: 6.82,
    tradedPrice: 96.71,
    cleanPrice: 96.71,
    accruedInterest: 0.00,
    dirtyPrice: 96.71,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & Wholesale Debt',
    maturityDate: '25 March 2027',
    tenorYears: 0.50,
    payoutFrequency: 'Zero-Coupon',
    minInvestment: 25000,
    taxStatus: 'STCG as per income tax slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -32,
    dailyTurnoverCr: 2200,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 0,
    modifiedDurationYears: 0.50,
    macaulayDurationYears: 0.50,
    convexity: 0.25,
    summary: 'Half-year sovereign paper providing guaranteed cash yield and zero credit default risk.'
  },
  {
    id: 'tbill-364d-2027',
    name: '364-Day Government Treasury Bill',
    issuer: 'Government of India (GOI / RBI)',
    isin: 'IN002024Z036',
    category: 'Treasury Bill',
    subCategory: 'T-Bill',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (100% RBI Guarantee)',
    couponRatePct: 0.00,
    ytmPct: 6.90,
    tradedPrice: 93.55,
    cleanPrice: 93.55,
    accruedInterest: 0.00,
    dirtyPrice: 93.55,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & Wholesale Debt',
    maturityDate: '23 September 2027',
    tenorYears: 1.00,
    payoutFrequency: 'Zero-Coupon',
    minInvestment: 25000,
    taxStatus: 'STCG as per income tax slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -24,
    dailyTurnoverCr: 3100,
    liquidityTag: 'Highly Liquid',
    daysSinceLastCoupon: 0,
    modifiedDurationYears: 0.98,
    macaulayDurationYears: 1.00,
    convexity: 0.98,
    summary: '1-Year sovereign discount paper offering predictable risk-free returns superior to bank savings deposits.'
  },

  // 3. STATE DEVELOPMENT LOANS (SDLS - SUB-SOVEREIGN PAPERS WITH SPREAD)
  {
    id: 'sdl-maha-742-2034',
    name: '7.42% Maharashtra SDL 2034',
    issuer: 'Government of Maharashtra (State Govt)',
    isin: 'IN2220230045',
    category: 'State Development Loan',
    subCategory: 'SDL',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (State Govt / RBI Serviced)',
    couponRatePct: 7.42,
    ytmPct: 7.42,
    tradedPrice: 100.15,
    cleanPrice: 100.15,
    accruedInterest: 0.52,
    dirtyPrice: 100.67,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & NSE/BSE',
    maturityDate: '24 May 2034',
    tenorYears: 8,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 28,
    dailyTurnoverCr: 650,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 51,
    modifiedDurationYears: 6.75,
    macaulayDurationYears: 7.00,
    convexity: 54.8,
    summary: 'State development loan from India’s highest GSDP state offering +28 bps attractive spread over Central G-Sec.'
  },
  {
    id: 'sdl-guj-745-2033',
    name: '7.45% Gujarat SDL 2033',
    issuer: 'Government of Gujarat (State Govt)',
    isin: 'IN1520230012',
    category: 'State Development Loan',
    subCategory: 'SDL',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (State Govt / RBI Serviced)',
    couponRatePct: 7.45,
    ytmPct: 7.45,
    tradedPrice: 100.20,
    cleanPrice: 100.20,
    accruedInterest: 0.48,
    dirtyPrice: 100.68,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & NSE/BSE',
    maturityDate: '15 June 2033',
    tenorYears: 7,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 31,
    dailyTurnoverCr: 580,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 47,
    modifiedDurationYears: 6.10,
    macaulayDurationYears: 6.32,
    convexity: 45.3,
    summary: 'Fiscal powerhouse state loan with stellar debt-to-GSDP discipline and pristine RBI repayment record.'
  },
  {
    id: 'sdl-tn-748-2034',
    name: '7.48% Tamil Nadu SDL 2034',
    issuer: 'Government of Tamil Nadu (State Govt)',
    isin: 'IN3120230089',
    category: 'State Development Loan',
    subCategory: 'SDL',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (State Govt / RBI Serviced)',
    couponRatePct: 7.48,
    ytmPct: 7.48,
    tradedPrice: 100.10,
    cleanPrice: 100.10,
    accruedInterest: 0.60,
    dirtyPrice: 100.70,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & NSE/BSE',
    maturityDate: '10 July 2034',
    tenorYears: 8,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 34,
    dailyTurnoverCr: 490,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 59,
    modifiedDurationYears: 6.80,
    macaulayDurationYears: 7.05,
    convexity: 55.6,
    summary: 'Manufacturing hub state development loan trading at +34 bps premium yield with institutional interest.'
  },
  {
    id: 'sdl-ka-750-2033',
    name: '7.50% Karnataka SDL 2033',
    issuer: 'Government of Karnataka (State Govt)',
    isin: 'IN1920230067',
    category: 'State Development Loan',
    subCategory: 'SDL',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (State Govt / RBI Serviced)',
    couponRatePct: 7.50,
    ytmPct: 7.50,
    tradedPrice: 100.18,
    cleanPrice: 100.18,
    accruedInterest: 0.55,
    dirtyPrice: 100.73,
    faceValue: 100,
    exchange: 'CCIL NDS-OM & NSE/BSE',
    maturityDate: '18 August 2033',
    tenorYears: 7,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: 36,
    dailyTurnoverCr: 520,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 54,
    modifiedDurationYears: 6.20,
    macaulayDurationYears: 6.43,
    convexity: 46.8,
    summary: 'Tech capital state bond providing +36 bps yield pickup over Central G-Sec with complete RBI settlement guarantee.'
  },

  // 4. PSU TAX-FREE BONDS (100% TAX EXEMPT UNDER SECTION 10(15)(iv)(h))
  {
    id: 'bond-psu-rec-754',
    name: 'REC Limited 7.54% Tax-Free Bond 2033',
    issuer: 'REC Limited (Maharatna PSU)',
    isin: 'INE020B07HQ5',
    category: 'Tax-Free Bond',
    subCategory: 'PSU Tax-Free',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / ICRA AAA',
    couponRatePct: 7.54,
    ytmPct: 5.48,
    tradedPrice: 1185.00,
    cleanPrice: 1185.00,
    accruedInterest: 14.50,
    dirtyPrice: 1199.50,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '19 December 2033',
    tenorYears: 7,
    payoutFrequency: 'Annual Interest',
    minInvestment: 11850,
    taxStatus: '100% Tax-Free under Sec 10(15)(iv)(h)',
    isSeniorSecured: true,
    benchmarkSpreadBps: -166,
    dailyTurnoverCr: 320,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 70,
    modifiedDurationYears: 5.20,
    macaulayDurationYears: 5.48,
    convexity: 36.2,
    summary: '100% Tax-Free PSU Infrastructure Bond. 5.48% tax-free yield equates to 7.83% pre-tax in 30% HNI tax bracket.'
  },
  {
    id: 'bond-psu-pfc-762',
    name: 'PFC Limited 7.62% Tax-Free Bond 2034',
    issuer: 'Power Finance Corporation (Maharatna PSU)',
    isin: 'INE134E07198',
    category: 'Tax-Free Bond',
    subCategory: 'PSU Tax-Free',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / CARE AAA',
    couponRatePct: 7.62,
    ytmPct: 5.52,
    tradedPrice: 1201.00,
    cleanPrice: 1201.00,
    accruedInterest: 16.20,
    dirtyPrice: 1217.20,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '22 March 2034',
    tenorYears: 8,
    payoutFrequency: 'Annual Interest',
    minInvestment: 12010,
    taxStatus: '100% Tax-Free under Sec 10(15)(iv)(h)',
    isSeniorSecured: true,
    benchmarkSpreadBps: -162,
    dailyTurnoverCr: 290,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 77,
    modifiedDurationYears: 5.80,
    macaulayDurationYears: 6.12,
    convexity: 44.1,
    summary: 'Flagship power infra bond with zero TDS deduction and zero tax liability on annual interest income.'
  },
  {
    id: 'bond-psu-nhai-760',
    name: 'NHAI 7.60% Tax-Free Highway Bond 2032',
    issuer: 'National Highways Authority of India (GOI)',
    isin: 'INE906B07DE2',
    category: 'Tax-Free Bond',
    subCategory: 'PSU Tax-Free',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / ICRA AAA',
    couponRatePct: 7.60,
    ytmPct: 5.42,
    tradedPrice: 1192.00,
    cleanPrice: 1192.00,
    accruedInterest: 15.10,
    dirtyPrice: 1207.10,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '11 January 2032',
    tenorYears: 6,
    payoutFrequency: 'Annual Interest',
    minInvestment: 11920,
    taxStatus: '100% Tax-Free under Sec 10(15)(iv)(h)',
    isSeniorSecured: true,
    benchmarkSpreadBps: -172,
    dailyTurnoverCr: 410,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 72,
    modifiedDurationYears: 4.90,
    macaulayDurationYears: 5.16,
    convexity: 32.5,
    summary: 'Sovereign-backed highway infrastructure bond with superior secondary market trading liquidity.'
  },
  {
    id: 'bond-psu-irfc-753',
    name: 'IRFC 7.53% Tax-Free Railway Bond 2031',
    issuer: 'Indian Railway Finance Corp (Govt of India)',
    isin: 'INE053F07802',
    category: 'Tax-Free Bond',
    subCategory: 'PSU Tax-Free',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA Rated',
    couponRatePct: 7.53,
    ytmPct: 5.39,
    tradedPrice: 1178.00,
    cleanPrice: 1178.00,
    accruedInterest: 13.80,
    dirtyPrice: 1191.80,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '15 October 2031',
    tenorYears: 5,
    payoutFrequency: 'Annual Interest',
    minInvestment: 11780,
    taxStatus: '100% Tax-Free under Sec 10(15)(iv)(h)',
    isSeniorSecured: true,
    benchmarkSpreadBps: -175,
    dailyTurnoverCr: 380,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 67,
    modifiedDurationYears: 4.30,
    macaulayDurationYears: 4.53,
    convexity: 25.1,
    summary: 'Indian Railways financing paper backed by sovereign lease assets. 100% tax exemption on interest.'
  },
  {
    id: 'bond-psu-hudco-758',
    name: 'HUDCO 7.58% Tax-Free Housing Bond 2034',
    issuer: 'Housing and Urban Development Corp (PSU)',
    isin: 'INE031A07823',
    category: 'Tax-Free Bond',
    subCategory: 'PSU Tax-Free',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'ICRA AAA / CARE AAA',
    couponRatePct: 7.58,
    ytmPct: 5.50,
    tradedPrice: 1198.00,
    cleanPrice: 1198.00,
    accruedInterest: 15.60,
    dirtyPrice: 1213.60,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '14 February 2034',
    tenorYears: 8,
    payoutFrequency: 'Annual Interest',
    minInvestment: 11980,
    taxStatus: '100% Tax-Free under Sec 10(15)(iv)(h)',
    isSeniorSecured: true,
    benchmarkSpreadBps: -164,
    dailyTurnoverCr: 210,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 75,
    modifiedDurationYears: 5.60,
    macaulayDurationYears: 5.91,
    convexity: 41.2,
    summary: 'Housing and urban infrastructure financing PSU paper offering stable zero-tax cash flow.'
  },

  // 5. SENIOR SECURED CORPORATE NCDS (CRISIL / ICRA AAA & AA+)
  {
    id: 'bond-ncd-lt-915',
    name: 'L&T Finance Secured Corporate NCD',
    issuer: 'L&T Finance Limited',
    isin: 'INE498L07345',
    category: 'Secured NCD',
    subCategory: 'Corporate NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / ICRA AAA',
    couponRatePct: 9.15,
    ytmPct: 9.12,
    tradedPrice: 1012.50,
    cleanPrice: 1012.50,
    accruedInterest: 18.20,
    dirtyPrice: 1030.70,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '24 March 2029',
    tenorYears: 3,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable (10% TDS applicable)',
    isSeniorSecured: true,
    benchmarkSpreadBps: 198,
    dailyTurnoverCr: 180,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 73,
    modifiedDurationYears: 2.80,
    macaulayDurationYears: 3.05,
    convexity: 10.4,
    summary: 'AAA-rated senior secured corporate NCD backed by first charge on Larsen & Toubro Group assets.'
  },
  {
    id: 'bond-ncd-hdfc-885',
    name: 'HDFC Bank 8.85% Tier-2 Senior NCD',
    issuer: 'HDFC Bank Limited',
    isin: 'INE040A08035',
    category: 'Secured NCD',
    subCategory: 'Corporate NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / CARE AAA',
    couponRatePct: 8.85,
    ytmPct: 8.82,
    tradedPrice: 1005.00,
    cleanPrice: 1005.00,
    accruedInterest: 12.40,
    dirtyPrice: 1017.40,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '15 September 2031',
    tenorYears: 5,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    benchmarkSpreadBps: 168,
    dailyTurnoverCr: 350,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 51,
    modifiedDurationYears: 4.20,
    macaulayDurationYears: 4.57,
    convexity: 23.8,
    summary: 'Fortress balance sheet bank paper offering robust yield with highest safety tier in India.'
  },
  {
    id: 'bond-ncd-tata-890',
    name: 'Tata Capital 8.90% Secured Corporate NCD',
    issuer: 'Tata Capital Limited',
    isin: 'INE306N07LA4',
    category: 'Secured NCD',
    subCategory: 'Corporate NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'ICRA AAA / CRISIL AAA',
    couponRatePct: 8.90,
    ytmPct: 8.88,
    tradedPrice: 1008.00,
    cleanPrice: 1008.00,
    accruedInterest: 14.80,
    dirtyPrice: 1022.80,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '12 November 2028',
    tenorYears: 2,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    benchmarkSpreadBps: 174,
    dailyTurnoverCr: 140,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 61,
    modifiedDurationYears: 2.60,
    macaulayDurationYears: 2.83,
    convexity: 9.1,
    summary: 'Secured paper backed by Tata Group brand trust, tangible asset security, and reliable annual coupon flow.'
  },
  {
    id: 'bond-ncd-shriram-925',
    name: 'Shriram Finance 9.25% Senior Secured NCD',
    issuer: 'Shriram Finance Limited',
    isin: 'INE721A07QR2',
    category: 'Secured NCD',
    subCategory: 'Corporate NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'CRISIL AA+ / India Ratings AA+',
    couponRatePct: 9.25,
    ytmPct: 9.22,
    tradedPrice: 1002.00,
    cleanPrice: 1002.00,
    accruedInterest: 16.50,
    dirtyPrice: 1018.50,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '18 July 2027',
    tenorYears: 1,
    payoutFrequency: 'Monthly / Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    benchmarkSpreadBps: 208,
    dailyTurnoverCr: 120,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 65,
    modifiedDurationYears: 1.85,
    macaulayDurationYears: 2.02,
    convexity: 4.8,
    summary: 'High-yield secured retail vehicle asset financier NCD yielding +208 bps above sovereign benchmarks.'
  },
  {
    id: 'bond-ncd-chola-895',
    name: 'Cholamandalam Inv 8.95% Secured NCD',
    issuer: 'Cholamandalam Investment & Finance Co.',
    isin: 'INE121A07RS8',
    category: 'Secured NCD',
    subCategory: 'Corporate NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'CARE AA+ / ICRA AA+',
    couponRatePct: 8.95,
    ytmPct: 8.92,
    tradedPrice: 1004.50,
    cleanPrice: 1004.50,
    accruedInterest: 11.20,
    dirtyPrice: 1015.70,
    faceValue: 1000,
    exchange: 'NSE Listed',
    maturityDate: '28 October 2028',
    tenorYears: 2,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    benchmarkSpreadBps: 178,
    dailyTurnoverCr: 95,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 46,
    modifiedDurationYears: 2.40,
    macaulayDurationYears: 2.61,
    convexity: 7.9,
    summary: 'Murugappa Group flagship vehicle and LAP financier with stellar asset quality and attractive yield.'
  },

  // 6. SOVEREIGN GOLD BONDS (SGB - 2.50% P.A. + TAX-FREE CAPITAL GAINS)
  {
    id: 'sgb-2020-vii-28oct',
    name: 'SGB 2020-21 Series VII (SGB28OCT)',
    issuer: 'Reserve Bank of India (RBI / GOI)',
    isin: 'IN0020200237',
    category: 'Sovereign Gold Bond',
    subCategory: 'SGB',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India / 24K Gold Backed)',
    couponRatePct: 2.50,
    ytmPct: 6.85,
    tradedPrice: 6990.00,
    cleanPrice: 6990.00,
    accruedInterest: 32.50,
    dirtyPrice: 7022.50,
    faceValue: 5051,
    exchange: 'NSE & BSE Listed (SGB Segment)',
    maturityDate: '27 October 2028',
    tenorYears: 2,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 6990,
    taxStatus: '100% Tax-Exempt Capital Gains at Maturity (Sec 47(viic))',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -29,
    dailyTurnoverCr: 85,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 95,
    modifiedDurationYears: 1.95,
    macaulayDurationYears: 2.00,
    convexity: 4.1,
    summary: 'RBI Sovereign Gold Bond trading at secondary discount to MCX spot gold. 2.50% semi-annual interest + tax-free redemption.'
  },
  {
    id: 'sgb-2021-ix-29feb',
    name: 'SGB 2021-22 Series IX (SGB29FEB)',
    issuer: 'Reserve Bank of India (RBI / GOI)',
    isin: 'IN0020210251',
    category: 'Sovereign Gold Bond',
    subCategory: 'SGB',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India / 24K Gold Backed)',
    couponRatePct: 2.50,
    ytmPct: 6.92,
    tradedPrice: 7040.00,
    cleanPrice: 7040.00,
    accruedInterest: 28.10,
    dirtyPrice: 7068.10,
    faceValue: 4791,
    exchange: 'NSE & BSE Listed (SGB Segment)',
    maturityDate: '28 February 2029',
    tenorYears: 3,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 7040,
    taxStatus: '100% Tax-Exempt Capital Gains at Maturity (Sec 47(viic))',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -22,
    dailyTurnoverCr: 110,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 82,
    modifiedDurationYears: 2.85,
    macaulayDurationYears: 2.92,
    convexity: 8.8,
    summary: 'High-liquidity SGB tranche with active market depth and 2.50% sovereign cash coupon.'
  },
  {
    id: 'sgb-2021-v-29sep',
    name: 'SGB 2021-22 Series V (SGB29SEP)',
    issuer: 'Reserve Bank of India (RBI / GOI)',
    isin: 'IN0020210178',
    category: 'Sovereign Gold Bond',
    subCategory: 'SGB',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India / 24K Gold Backed)',
    couponRatePct: 2.50,
    ytmPct: 7.05,
    tradedPrice: 6920.00,
    cleanPrice: 6920.00,
    accruedInterest: 31.40,
    dirtyPrice: 6951.40,
    faceValue: 4790,
    exchange: 'NSE & BSE Listed (SGB Segment)',
    maturityDate: '30 September 2029',
    tenorYears: 3,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 6920,
    taxStatus: '100% Tax-Exempt Capital Gains at Maturity (Sec 47(viic))',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -9,
    dailyTurnoverCr: 95,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 91,
    modifiedDurationYears: 2.90,
    macaulayDurationYears: 2.97,
    convexity: 9.2,
    summary: 'Deep-discount secondary market SGB tranche providing annualized yield enhancement above physical gold.'
  },
  {
    id: 'sgb-2022-i-30jun',
    name: 'SGB 2022-23 Series I (SGB30JUN)',
    issuer: 'Reserve Bank of India (RBI / GOI)',
    isin: 'IN0020220052',
    category: 'Sovereign Gold Bond',
    subCategory: 'SGB',
    market: 'Indian',
    currency: '₹',
    creditRating: 'SOVEREIGN',
    agencyRating: 'Sovereign (Govt of India / 24K Gold Backed)',
    couponRatePct: 2.50,
    ytmPct: 6.88,
    tradedPrice: 7080.00,
    cleanPrice: 7080.00,
    accruedInterest: 25.60,
    dirtyPrice: 7105.60,
    faceValue: 5041,
    exchange: 'NSE & BSE Listed (SGB Segment)',
    maturityDate: '30 June 2030',
    tenorYears: 4,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 7080,
    taxStatus: '100% Tax-Exempt Capital Gains at Maturity (Sec 47(viic))',
    isSeniorSecured: true,
    isSovereign: true,
    benchmarkSpreadBps: -26,
    dailyTurnoverCr: 130,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 75,
    modifiedDurationYears: 3.75,
    macaulayDurationYears: 3.84,
    convexity: 15.2,
    summary: '4-Year remaining maturity SGB with substantial retail trading volume and zero capital gains tax at exit.'
  },

  // 7. CORPORATE FIXED DEPOSITS (HIGH YIELD BANK / NBFC)
  {
    id: 'bond-in-aaa-3',
    name: 'Shriram Finance Cumulative Senior FD',
    issuer: 'Shriram Finance Limited',
    isin: 'FD-SHRIRAM-2027',
    category: 'Corporate FD',
    subCategory: 'Corporate FD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / India Ratings AA+',
    couponRatePct: 8.80,
    ytmPct: 8.80,
    tradedPrice: 10000.00,
    cleanPrice: 10000.00,
    accruedInterest: 0.00,
    dirtyPrice: 10000.00,
    faceValue: 10000,
    exchange: 'BSE Listed Direct',
    maturityDate: '15 September 2027',
    tenorYears: 2,
    payoutFrequency: 'Cumulative at Maturity',
    minInvestment: 5000,
    taxStatus: 'Taxable (Section 194A)',
    isSeniorSecured: true,
    benchmarkSpreadBps: 166,
    dailyTurnoverCr: 60,
    liquidityTag: 'Illiquid',
    daysSinceLastCoupon: 0,
    modifiedDurationYears: 1.84,
    macaulayDurationYears: 2.00,
    convexity: 4.2,
    summary: 'Highest-yielding AAA corporate fixed deposit with guaranteed compounding returns.'
  },
  {
    id: 'bond-in-aaa-4',
    name: 'NTPC 8.48% Tax-Free Infrastructure Bond',
    issuer: 'NTPC Limited',
    isin: 'INE733E07097',
    category: 'Tax-Free Bond',
    subCategory: 'PSU Tax-Free',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA Rated',
    couponRatePct: 8.48,
    ytmPct: 5.65,
    tradedPrice: 1245.00,
    cleanPrice: 1245.00,
    accruedInterest: 17.50,
    dirtyPrice: 1262.50,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '16 December 2028',
    tenorYears: 2,
    payoutFrequency: 'Annual Interest',
    minInvestment: 12450,
    taxStatus: '100% Tax-Free Interest (Sec 10(15))',
    isSeniorSecured: true,
    benchmarkSpreadBps: -149,
    dailyTurnoverCr: 190,
    liquidityTag: 'Moderate',
    daysSinceLastCoupon: 75,
    modifiedDurationYears: 2.10,
    macaulayDurationYears: 2.22,
    convexity: 5.4,
    summary: '100% Tax-Free PSU Infrastructure Bond issued under Section 10(15)(iv)(h).'
  },

  // AA RATED (High Safety)
  {
    id: 'bond-in-aa-1',
    name: 'Muthoot Finance Secured NCD Series VI',
    issuer: 'Muthoot Finance Limited',
    isin: 'INE414G07EE2',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'ICRA AA+ / CRISIL AA+',
    couponRatePct: 9.75,
    ytmPct: 9.68,
    tradedPrice: 1008.20,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '18 October 2028',
    tenorYears: 2,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'High-yield monthly interest secured NCD backed 100% by physical gold collateral.'
  },
  {
    id: 'bond-in-aa-2',
    name: 'InCred Financial Senior Secured NCD',
    issuer: 'InCred Financial Services Ltd',
    isin: 'INE945W07324',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'CRISIL AA- Rated',
    couponRatePct: 10.30,
    ytmPct: 10.25,
    tradedPrice: 1002.50,
    faceValue: 1000,
    exchange: 'NSE Listed',
    maturityDate: '12 January 2028',
    tenorYears: 2,
    payoutFrequency: 'Quarterly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Senior secured asset-backed NCD with attractive 10.30% p.a. quarterly payouts.'
  },
  {
    id: 'bond-in-aa-3',
    name: 'Navi Finserv Secured NCD Series II',
    issuer: 'Navi Finserv Limited',
    isin: 'INE342T07047',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'CRISIL A+ / India Ratings AA-',
    couponRatePct: 10.40,
    ytmPct: 10.35,
    tradedPrice: 1005.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '08 June 2027',
    tenorYears: 1,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Monthly income tech-driven fintech NCD backed by digital consumer loan book.'
  },

  // A RATED (Adequate Safety)
  {
    id: 'bond-in-a-1',
    name: 'Piramal Capital Secured Corporate NCD',
    issuer: 'Piramal Capital & Housing Finance',
    isin: 'INE516Y07370',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'A',
    agencyRating: 'CARE A / ICRA A+',
    couponRatePct: 11.10,
    ytmPct: 11.05,
    tradedPrice: 1001.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '23 November 2027',
    tenorYears: 1,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'High-yield housing finance NCD offering 11.10% p.a. returns with secured pool.'
  },
  {
    id: 'bond-in-a-2',
    name: 'Spandana Spoorthy Senior Secured Note',
    issuer: 'Spandana Spoorthy Financial Ltd',
    isin: 'INE572J07530',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'A',
    agencyRating: 'ICRA A- Rated',
    couponRatePct: 11.75,
    ytmPct: 11.80,
    tradedPrice: 996.50,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '15 March 2027',
    tenorYears: 1,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Microfinance lender senior secured NCD with monthly income yield above 11.75%.'
  },
  {
    id: 'bond-in-a-3',
    name: 'KreditBee Financial Senior Note',
    issuer: 'Krazybee Services Private Ltd',
    isin: 'INE071S07028',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'A',
    agencyRating: 'CARE A Rated',
    couponRatePct: 12.00,
    ytmPct: 12.10,
    tradedPrice: 992.00,
    faceValue: 1000,
    exchange: 'NSE Listed',
    maturityDate: '20 August 2027',
    tenorYears: 1,
    payoutFrequency: 'Quarterly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Digital lending platform high-yield secured note targeting 12.00% annual coupon.'
  },

  // BBB RATED (Moderate Risk)
  {
    id: 'bond-in-bbb-1',
    name: 'Indiabulls Commercial Credit NCD',
    issuer: 'Indiabulls Commercial Credit Ltd',
    isin: 'INE244L07218',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'BBB',
    agencyRating: 'CRISIL BBB+ / Brickwork BBB',
    couponRatePct: 12.80,
    ytmPct: 12.95,
    tradedPrice: 988.50,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '14 May 2027',
    tenorYears: 1,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Commercial lending high-yield instrument providing 12.80% p.a. for risk-tolerant investors.'
  },
  {
    id: 'bond-in-bbb-2',
    name: 'Auxilo Finserve High Yield NCD',
    issuer: 'Auxilo Finserve Private Ltd',
    isin: 'INE002R07019',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'BBB',
    agencyRating: 'CARE BBB+ Rated',
    couponRatePct: 13.20,
    ytmPct: 13.40,
    tradedPrice: 985.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '30 November 2027',
    tenorYears: 1,
    payoutFrequency: 'Quarterly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: false,
    summary: 'Education fintech bond offering 13.20% coupon interest with moderate risk profile.'
  },

  // BB RATED (High Yield / Speculative)
  {
    id: 'bond-in-bb-1',
    name: 'Northern Arc High Yield Micro-Credit Note',
    issuer: 'Northern Arc Capital Ltd',
    isin: 'INE850D07112',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'BB',
    agencyRating: 'ICRA BB+ Rated',
    couponRatePct: 14.10,
    ytmPct: 14.50,
    tradedPrice: 972.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '10 October 2026',
    tenorYears: 1,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: false,
    summary: 'High-yield speculative debt instrument offering 14.10% monthly cash flow returns.'
  }
];

export const US_BONDS_CATALOG: BondFDItem[] = [
  // AAA RATED (Highest Safety)
  {
    id: 'bond-us-aaa-1',
    name: 'US 10-Year Treasury Note (UST10Y)',
    issuer: 'United States Department of the Treasury',
    isin: 'US91282CJZ52',
    category: 'US Treasury',
    market: 'US',
    currency: '$',
    creditRating: 'AAA',
    agencyRating: 'Fitch AAA / Moody’s Aaa',
    couponRatePct: 4.25,
    ytmPct: 4.38,
    tradedPrice: 98.75,
    faceValue: 100,
    exchange: 'FINRA / NYSE Arca',
    maturityDate: '15 February 2034',
    tenorYears: 8,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 1000,
    taxStatus: 'Exempt from US State & Local Taxes',
    isSeniorSecured: true,
    summary: '10-Year Benchmark US Treasury Note backed full faith & credit of US Government.'
  },
  {
    id: 'bond-us-aaa-2',
    name: 'US 3-Month Treasury Bill (UST3M)',
    issuer: 'United States Department of the Treasury',
    isin: 'US912797LS66',
    category: 'US Treasury',
    market: 'US',
    currency: '$',
    creditRating: 'AAA',
    agencyRating: 'Fitch AAA Rated',
    couponRatePct: 5.25,
    ytmPct: 5.32,
    tradedPrice: 98.70,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '19 November 2026',
    tenorYears: 0.25,
    payoutFrequency: 'Discount at Maturity',
    minInvestment: 1000,
    taxStatus: 'Exempt from State Taxes',
    isSeniorSecured: true,
    summary: 'Ultra-safe short term liquid US T-Bill offering 5.32% risk-free dollar yield.'
  },
  {
    id: 'bond-us-aaa-3',
    name: 'Microsoft Corporation 4.20% Senior Note',
    issuer: 'Microsoft Corporation (MSFT)',
    isin: 'US594918CD72',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AAA',
    agencyRating: 'S&P AAA / Moody’s Aaa',
    couponRatePct: 4.20,
    ytmPct: 4.65,
    tradedPrice: 96.80,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '03 November 2035',
    tenorYears: 9,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Standard US Withholding Tax',
    isSeniorSecured: true,
    summary: 'Pristine AAA tech corporate bond backed by Microsoft balance sheet.'
  },

  // AA RATED (High Safety)
  {
    id: 'bond-us-aa-1',
    name: 'Apple Inc. 3.85% Senior Unsecured Note',
    issuer: 'Apple Inc. (AAPL)',
    isin: 'US037833DV70',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AA',
    agencyRating: 'S&P AA+ / Moody’s Aa1',
    couponRatePct: 3.85,
    ytmPct: 4.82,
    tradedPrice: 92.40,
    faceValue: 100,
    exchange: 'FINRA / NYSE',
    maturityDate: '04 August 2031',
    tenorYears: 5,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'High-grade tech senior note with strong cash flow coverage.'
  },
  {
    id: 'bond-us-aa-2',
    name: 'JPMorgan Chase & Co. 5.15% Fixed Note',
    issuer: 'JPMorgan Chase & Co.',
    isin: 'US46647PAA28',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AA',
    agencyRating: 'Fitch AA- / S&P A+',
    couponRatePct: 5.15,
    ytmPct: 5.45,
    tradedPrice: 98.20,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '16 September 2028',
    tenorYears: 2,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Premier banking group fixed rate corporate bond yielding 5.45% YTM.'
  },
  {
    id: 'bond-us-aa-3',
    name: 'Amazon.com, Inc. 4.50% Corporate Bond',
    issuer: 'Amazon.com, Inc. (AMZN)',
    isin: 'US023135CY74',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AA',
    agencyRating: 'S&P AA- Rated',
    couponRatePct: 4.50,
    ytmPct: 5.10,
    tradedPrice: 95.80,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '01 December 2032',
    tenorYears: 6,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'E-commerce & cloud leader high grade debt offering steady annual income.'
  },

  // A RATED (Adequate Safety)
  {
    id: 'bond-us-a-1',
    name: 'Goldman Sachs Group 5.80% Fixed Note',
    issuer: 'The Goldman Sachs Group, Inc.',
    isin: 'US38141GZX33',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'A',
    agencyRating: 'S&P A / Moody’s A2',
    couponRatePct: 5.80,
    ytmPct: 6.05,
    tradedPrice: 99.10,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '24 October 2027',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Investment banking giant fixed income note with attractive 6.05% YTM yield.'
  },
  {
    id: 'bond-us-a-2',
    name: 'Boeing Company 5.95% Senior Note',
    issuer: 'The Boeing Company (BA)',
    isin: 'US097023DA21',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'A',
    agencyRating: 'Fitch BBB+ / S&P A-',
    couponRatePct: 5.95,
    ytmPct: 6.35,
    tradedPrice: 98.00,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '01 May 2030',
    tenorYears: 4,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Aerospace corporate bond offering elevated yield above 6.35%.'
  },

  // BBB RATED (Moderate Risk)
  {
    id: 'bond-us-bbb-1',
    name: 'Ford Motor Credit 6.875% Senior Note',
    issuer: 'Ford Motor Credit Company LLC',
    isin: 'US345397ZX12',
    category: 'High Yield Note',
    market: 'US',
    currency: '$',
    creditRating: 'BBB',
    agencyRating: 'S&P BBB- / Fitch BBB',
    couponRatePct: 6.875,
    ytmPct: 7.25,
    tradedPrice: 98.50,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '12 November 2027',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Automotive credit arm note delivering high coupon income of 6.875%.'
  },
  {
    id: 'bond-us-bbb-2',
    name: 'General Motors Financial 6.25% Note',
    issuer: 'General Motors Financial Co.',
    isin: 'US37045XCF88',
    category: 'High Yield Note',
    market: 'US',
    currency: '$',
    creditRating: 'BBB',
    agencyRating: 'Moody’s Baa2 / S&P BBB',
    couponRatePct: 6.25,
    ytmPct: 6.70,
    tradedPrice: 99.00,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '08 April 2028',
    tenorYears: 2,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'US auto financing high-yield corporate bond with solid cash flow buffer.'
  },

  // BB RATED (High Yield / Speculative)
  {
    id: 'bond-us-bb-1',
    name: 'Occidental Petroleum 7.875% High Yield Note',
    issuer: 'Occidental Petroleum Corp (OXY)',
    isin: 'US674599CH89',
    category: 'High Yield Note',
    market: 'US',
    currency: '$',
    creditRating: 'BB',
    agencyRating: 'Fitch BB+ / Moody’s Ba1',
    couponRatePct: 7.875,
    ytmPct: 8.20,
    tradedPrice: 99.25,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '15 September 2026',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: false,
    summary: 'Energy sector high-yield bond offering 7.875% coupon for yield-seeking portfolios.'
  }
];
