export interface BondFDItem {
  id: string;
  name: string;
  issuer: string;
  isin: string;
  category: 'Government Bond' | 'Secured NCD' | 'Corporate FD' | 'Tax-Free Bond' | 'US Treasury' | 'US Corporate Bond' | 'High Yield Note';
  market: 'Indian' | 'US';
  currency: '₹' | '$';
  creditRating: 'AAA' | 'AA' | 'A' | 'BBB' | 'BB';
  agencyRating: string; // e.g. CRISIL AAA, ICRA AA+, CARE A, S&P BBB
  couponRatePct: number;
  ytmPct: number;
  tradedPrice: number;
  faceValue: number;
  exchange: string; // e.g. BSE Listed, NSE Listed, BSE & NSE, FINRA / NYSE
  maturityDate: string;
  tenorYears: number;
  payoutFrequency: string; // e.g. Monthly, Annual, Cumulative, Semi-Annual
  minInvestment: number;
  taxStatus: string;
  isSeniorSecured: boolean;
  summary: string;
}

export const INDIAN_BONDS_CATALOG: BondFDItem[] = [
  // AAA RATED (Highest Safety)
  {
    id: 'bond-in-aaa-1',
    name: '7.18% GS 2033 Sovereign G-Sec',
    issuer: 'Government of India (GOI)',
    isin: 'IN0020230085',
    category: 'Government Bond',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'Sovereign (Govt of India)',
    couponRatePct: 7.18,
    ytmPct: 7.14,
    tradedPrice: 100.25,
    faceValue: 100,
    exchange: 'NSE & BSE Listed (NDS-OM)',
    maturityDate: '14 August 2033',
    tenorYears: 7,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 10000,
    taxStatus: 'Taxable as per slab',
    isSeniorSecured: true,
    summary: '10-Year Benchmark Sovereign Government Bond backed 100% by RBI.'
  },
  {
    id: 'bond-in-aaa-2',
    name: 'L&T Finance Secured Corporate NCD',
    issuer: 'L&T Finance Limited',
    isin: 'INE498L07345',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / ICRA AAA',
    couponRatePct: 9.15,
    ytmPct: 9.12,
    tradedPrice: 1012.50,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '24 March 2029',
    tenorYears: 3,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable (10% TDS applicable)',
    isSeniorSecured: true,
    summary: 'AAA-rated secured corporate NCD backed by Larsen & Toubro Group assets.'
  },
  {
    id: 'bond-in-aaa-3',
    name: 'Shriram Finance Cumulative Senior FD',
    issuer: 'Shriram Finance Limited',
    isin: 'FD-SHRIRAM-2027',
    category: 'Corporate FD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA / India Ratings AA+',
    couponRatePct: 8.80,
    ytmPct: 8.80,
    tradedPrice: 10000.00,
    faceValue: 10000,
    exchange: 'BSE Listed Direct',
    maturityDate: '15 September 2027',
    tenorYears: 2,
    payoutFrequency: 'Cumulative at Maturity',
    minInvestment: 5000,
    taxStatus: 'Taxable (Section 194A)',
    isSeniorSecured: true,
    summary: 'Highest-yielding AAA corporate fixed deposit with guaranteed returns.'
  },
  {
    id: 'bond-in-aaa-4',
    name: 'NTPC 8.48% Tax-Free Infrastructure Bond',
    issuer: 'NTPC Limited',
    isin: 'INE733E07097',
    category: 'Tax-Free Bond',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AAA',
    agencyRating: 'CRISIL AAA Rated',
    couponRatePct: 8.48,
    ytmPct: 5.65,
    tradedPrice: 1245.00,
    faceValue: 1000,
    exchange: 'BSE & NSE Listed',
    maturityDate: '16 December 2028',
    tenorYears: 2,
    payoutFrequency: 'Annual Interest',
    minInvestment: 12450,
    taxStatus: '100% Tax-Free Interest (Sec 10(15))',
    isSeniorSecured: true,
    summary: '100% Tax-Free PSU Infrastructure Bond issued under Section 10(15)(iv)(h).'
  },

  // AA RATED (High Safety)
  {
    id: 'bond-in-aa-1',
    name: 'Muthoot Finance Secured NCD Series VI',
    issuer: 'Muthoot Finance Limited',
    isin: 'INE414G07EE2',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'ICRA AA+ / CRISIL AA+',
    couponRatePct: 9.75,
    ytmPct: 9.68,
    tradedPrice: 1008.20,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '18 October 2028',
    tenorYears: 2,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'High-yield monthly interest secured NCD backed 100% by physical gold collateral.'
  },
  {
    id: 'bond-in-aa-2',
    name: 'InCred Financial Senior Secured NCD',
    issuer: 'InCred Financial Services Ltd',
    isin: 'INE945W07324',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'CRISIL AA- Rated',
    couponRatePct: 10.30,
    ytmPct: 10.25,
    tradedPrice: 1002.50,
    faceValue: 1000,
    exchange: 'NSE Listed',
    maturityDate: '12 January 2028',
    tenorYears: 2,
    payoutFrequency: 'Quarterly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Senior secured asset-backed NCD with attractive 10.30% p.a. quarterly payouts.'
  },
  {
    id: 'bond-in-aa-3',
    name: 'Navi Finserv Secured NCD Series II',
    issuer: 'Navi Finserv Limited',
    isin: 'INE342T07047',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'AA',
    agencyRating: 'CRISIL A+ / India Ratings AA-',
    couponRatePct: 10.40,
    ytmPct: 10.35,
    tradedPrice: 1005.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '08 June 2027',
    tenorYears: 1,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Monthly income tech-driven fintech NCD backed by digital consumer loan book.'
  },

  // A RATED (Adequate Safety)
  {
    id: 'bond-in-a-1',
    name: 'Piramal Capital Secured Corporate NCD',
    issuer: 'Piramal Capital & Housing Finance',
    isin: 'INE516Y07370',
    category: 'Secured NCD',
    market: 'Indian',
    currency: '₹',
    creditRating: 'A',
    agencyRating: 'CARE A / ICRA A+',
    couponRatePct: 11.10,
    ytmPct: 11.05,
    tradedPrice: 1001.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '23 November 2027',
    tenorYears: 1,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'High-yield housing finance NCD offering 11.10% p.a. returns with secured pool.'
  },
  {
    id: 'bond-in-a-2',
    name: 'Spandana Spoorthy Senior Secured Note',
    issuer: 'Spandana Spoorthy Financial Ltd',
    isin: 'INE572J07530',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'A',
    agencyRating: 'ICRA A- Rated',
    couponRatePct: 11.75,
    ytmPct: 11.80,
    tradedPrice: 996.50,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '15 March 2027',
    tenorYears: 1,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Microfinance lender senior secured NCD with monthly income yield above 11.75%.'
  },
  {
    id: 'bond-in-a-3',
    name: 'KreditBee Financial Senior Note',
    issuer: 'Krazybee Services Private Ltd',
    isin: 'INE071S07028',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'A',
    agencyRating: 'CARE A Rated',
    couponRatePct: 12.00,
    ytmPct: 12.10,
    tradedPrice: 992.00,
    faceValue: 1000,
    exchange: 'NSE Listed',
    maturityDate: '20 August 2027',
    tenorYears: 1,
    payoutFrequency: 'Quarterly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Digital lending platform high-yield secured note targeting 12.00% annual coupon.'
  },

  // BBB RATED (Moderate Risk)
  {
    id: 'bond-in-bbb-1',
    name: 'Indiabulls Commercial Credit NCD',
    issuer: 'Indiabulls Commercial Credit Ltd',
    isin: 'INE244L07218',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'BBB',
    agencyRating: 'CRISIL BBB+ / Brickwork BBB',
    couponRatePct: 12.80,
    ytmPct: 12.95,
    tradedPrice: 988.50,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '14 May 2027',
    tenorYears: 1,
    payoutFrequency: 'Annual Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Commercial lending high-yield instrument providing 12.80% p.a. for risk-tolerant investors.'
  },
  {
    id: 'bond-in-bbb-2',
    name: 'Auxilo Finserve High Yield NCD',
    issuer: 'Auxilo Finserve Private Ltd',
    isin: 'INE002R07019',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'BBB',
    agencyRating: 'CARE BBB+ Rated',
    couponRatePct: 13.20,
    ytmPct: 13.40,
    tradedPrice: 985.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '30 November 2027',
    tenorYears: 1,
    payoutFrequency: 'Quarterly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: false,
    summary: 'Education fintech bond offering 13.20% coupon interest with moderate risk profile.'
  },

  // BB RATED (High Yield / Speculative)
  {
    id: 'bond-in-bb-1',
    name: 'Northern Arc High Yield Micro-Credit Note',
    issuer: 'Northern Arc Capital Ltd',
    isin: 'INE850D07112',
    category: 'High Yield Note',
    market: 'Indian',
    currency: '₹',
    creditRating: 'BB',
    agencyRating: 'ICRA BB+ Rated',
    couponRatePct: 14.10,
    ytmPct: 14.50,
    tradedPrice: 972.00,
    faceValue: 1000,
    exchange: 'BSE Listed',
    maturityDate: '10 October 2026',
    tenorYears: 1,
    payoutFrequency: 'Monthly Interest',
    minInvestment: 10000,
    taxStatus: 'Taxable',
    isSeniorSecured: false,
    summary: 'High-yield speculative debt instrument offering 14.10% monthly cash flow returns.'
  }
];

export const US_BONDS_CATALOG: BondFDItem[] = [
  // AAA RATED (Highest Safety)
  {
    id: 'bond-us-aaa-1',
    name: 'US 10-Year Treasury Note (UST10Y)',
    issuer: 'United States Department of the Treasury',
    isin: 'US91282CJZ52',
    category: 'US Treasury',
    market: 'US',
    currency: '$',
    creditRating: 'AAA',
    agencyRating: 'Fitch AAA / Moody’s Aaa',
    couponRatePct: 4.25,
    ytmPct: 4.38,
    tradedPrice: 98.75,
    faceValue: 100,
    exchange: 'FINRA / NYSE Arca',
    maturityDate: '15 February 2034',
    tenorYears: 8,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 1000,
    taxStatus: 'Exempt from US State & Local Taxes',
    isSeniorSecured: true,
    summary: '10-Year Benchmark US Treasury Note backed full faith & credit of US Government.'
  },
  {
    id: 'bond-us-aaa-2',
    name: 'US 3-Month Treasury Bill (UST3M)',
    issuer: 'United States Department of the Treasury',
    isin: 'US912797LS66',
    category: 'US Treasury',
    market: 'US',
    currency: '$',
    creditRating: 'AAA',
    agencyRating: 'Fitch AAA Rated',
    couponRatePct: 5.25,
    ytmPct: 5.32,
    tradedPrice: 98.70,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '19 November 2026',
    tenorYears: 0.25,
    payoutFrequency: 'Discount at Maturity',
    minInvestment: 1000,
    taxStatus: 'Exempt from State Taxes',
    isSeniorSecured: true,
    summary: 'Ultra-safe short term liquid US T-Bill offering 5.32% risk-free dollar yield.'
  },
  {
    id: 'bond-us-aaa-3',
    name: 'Microsoft Corporation 4.20% Senior Note',
    issuer: 'Microsoft Corporation (MSFT)',
    isin: 'US594918CD72',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AAA',
    agencyRating: 'S&P AAA / Moody’s Aaa',
    couponRatePct: 4.20,
    ytmPct: 4.65,
    tradedPrice: 96.80,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '03 November 2035',
    tenorYears: 9,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Standard US Withholding Tax',
    isSeniorSecured: true,
    summary: 'Pristine AAA tech corporate bond backed by Microsoft balance sheet.'
  },

  // AA RATED (High Safety)
  {
    id: 'bond-us-aa-1',
    name: 'Apple Inc. 3.85% Senior Unsecured Note',
    issuer: 'Apple Inc. (AAPL)',
    isin: 'US037833DV70',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AA',
    agencyRating: 'S&P AA+ / Moody’s Aa1',
    couponRatePct: 3.85,
    ytmPct: 4.82,
    tradedPrice: 92.40,
    faceValue: 100,
    exchange: 'FINRA / NYSE',
    maturityDate: '04 August 2031',
    tenorYears: 5,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'High-grade tech senior note with strong cash flow coverage.'
  },
  {
    id: 'bond-us-aa-2',
    name: 'JPMorgan Chase & Co. 5.15% Fixed Note',
    issuer: 'JPMorgan Chase & Co.',
    isin: 'US46647PAA28',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AA',
    agencyRating: 'Fitch AA- / S&P A+',
    couponRatePct: 5.15,
    ytmPct: 5.45,
    tradedPrice: 98.20,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '16 September 2028',
    tenorYears: 2,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Premier banking group fixed rate corporate bond yielding 5.45% YTM.'
  },
  {
    id: 'bond-us-aa-3',
    name: 'Amazon.com, Inc. 4.50% Corporate Bond',
    issuer: 'Amazon.com, Inc. (AMZN)',
    isin: 'US023135CY74',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'AA',
    agencyRating: 'S&P AA- Rated',
    couponRatePct: 4.50,
    ytmPct: 5.10,
    tradedPrice: 95.80,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '01 December 2032',
    tenorYears: 6,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'E-commerce & cloud leader high grade debt offering steady annual income.'
  },

  // A RATED (Adequate Safety)
  {
    id: 'bond-us-a-1',
    name: 'Goldman Sachs Group 5.80% Fixed Note',
    issuer: 'The Goldman Sachs Group, Inc.',
    isin: 'US38141GZX33',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'A',
    agencyRating: 'S&P A / Moody’s A2',
    couponRatePct: 5.80,
    ytmPct: 6.05,
    tradedPrice: 99.10,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '24 October 2027',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Investment banking giant fixed income note with attractive 6.05% YTM yield.'
  },
  {
    id: 'bond-us-a-2',
    name: 'Boeing Company 5.95% Senior Note',
    issuer: 'The Boeing Company (BA)',
    isin: 'US097023DA21',
    category: 'US Corporate Bond',
    market: 'US',
    currency: '$',
    creditRating: 'A',
    agencyRating: 'Fitch BBB+ / S&P A-',
    couponRatePct: 5.95,
    ytmPct: 6.35,
    tradedPrice: 98.00,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '01 May 2030',
    tenorYears: 4,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Aerospace corporate bond offering elevated yield above 6.35%.'
  },

  // BBB RATED (Moderate Risk)
  {
    id: 'bond-us-bbb-1',
    name: 'Ford Motor Credit 6.875% Senior Note',
    issuer: 'Ford Motor Credit Company LLC',
    isin: 'US345397ZX12',
    category: 'High Yield Note',
    market: 'US',
    currency: '$',
    creditRating: 'BBB',
    agencyRating: 'S&P BBB- / Fitch BBB',
    couponRatePct: 6.875,
    ytmPct: 7.25,
    tradedPrice: 98.50,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '12 November 2027',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'Automotive credit arm note delivering high coupon income of 6.875%.'
  },
  {
    id: 'bond-us-bbb-2',
    name: 'General Motors Financial 6.25% Note',
    issuer: 'General Motors Financial Co.',
    isin: 'US37045XCF88',
    category: 'High Yield Note',
    market: 'US',
    currency: '$',
    creditRating: 'BBB',
    agencyRating: 'Moody’s Baa2 / S&P BBB',
    couponRatePct: 6.25,
    ytmPct: 6.70,
    tradedPrice: 99.00,
    faceValue: 100,
    exchange: 'FINRA Listed',
    maturityDate: '08 April 2028',
    tenorYears: 2,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: true,
    summary: 'US auto financing high-yield corporate bond with solid cash flow buffer.'
  },

  // BB RATED (High Yield / Speculative)
  {
    id: 'bond-us-bb-1',
    name: 'Occidental Petroleum 7.875% High Yield Note',
    issuer: 'Occidental Petroleum Corp (OXY)',
    isin: 'US674599CH89',
    category: 'High Yield Note',
    market: 'US',
    currency: '$',
    creditRating: 'BB',
    agencyRating: 'Fitch BB+ / Moody’s Ba1',
    couponRatePct: 7.875,
    ytmPct: 8.20,
    tradedPrice: 99.25,
    faceValue: 100,
    exchange: 'NYSE Listed',
    maturityDate: '15 September 2026',
    tenorYears: 1,
    payoutFrequency: 'Semi-Annual',
    minInvestment: 2000,
    taxStatus: 'Taxable',
    isSeniorSecured: false,
    summary: 'Energy sector high-yield bond offering 7.875% coupon for yield-seeking portfolios.'
  }
];
