import type { Asset } from '../types/portfolio';

export const INITIAL_ASSET_CATALOG: Asset[] = [
  // ==========================================
  // 1. TOP INDIAN EQUITIES (NSE / BSE NIFTY 50 & KEY SECTOR LEADERS)
  // ==========================================
  {
    id: 'hdfcbank',
    ticker: 'HDFCBANK.NS',
    name: 'HDFC Bank Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 1612.40,
    change24h: 0.95,
    change24hAmount: 15.20,
    annualizedReturn: 16.8,
    annualizedVol: 18.5,
    beta: 0.98,
    weight: 15,
    color: '#1e40af',
    currency: '₹'
  },
  {
    id: 'reliance',
    ticker: 'RELIANCE.NS',
    name: 'Reliance Industries Ltd.',
    category: 'Equities',
    market: 'NSE India',
    price: 2980.10,
    change24h: 0.82,
    change24hAmount: 24.25,
    annualizedReturn: 18.2,
    annualizedVol: 21.3,
    beta: 0.92,
    weight: 15,
    color: '#10b981',
    currency: '₹'
  },
  {
    id: 'icicibank',
    ticker: 'ICICIBANK.NS',
    name: 'ICICI Bank Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 1215.80,
    change24h: 1.42,
    change24hAmount: 17.00,
    annualizedReturn: 24.5,
    annualizedVol: 22.1,
    beta: 1.10,
    weight: 10,
    color: '#c2410c',
    currency: '₹'
  },
  {
    id: 'tcs',
    ticker: 'TCS.NS',
    name: 'Tata Consultancy Services',
    category: 'Equities',
    market: 'NSE India',
    price: 4280.50,
    change24h: 0.75,
    change24hAmount: 31.80,
    annualizedReturn: 17.4,
    annualizedVol: 17.8,
    beta: 0.78,
    weight: 0,
    color: '#4f46e5',
    currency: '₹'
  },
  {
    id: 'infy',
    ticker: 'INFY.NS',
    name: 'Infosys Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 1825.40,
    change24h: 1.12,
    change24hAmount: 20.20,
    annualizedReturn: 16.5,
    annualizedVol: 19.8,
    beta: 0.85,
    weight: 0,
    color: '#06b6d4',
    currency: '₹'
  },
  {
    id: 'bhartiartl',
    ticker: 'BHARTIARTL.NS',
    name: 'Bharti Airtel Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 1540.20,
    change24h: 1.85,
    change24hAmount: 28.00,
    annualizedReturn: 28.6,
    annualizedVol: 22.5,
    beta: 0.82,
    weight: 0,
    color: '#e11d48',
    currency: '₹'
  },
  {
    id: 'itc',
    ticker: 'ITC.NS',
    name: 'ITC Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 495.60,
    change24h: 0.45,
    change24hAmount: 2.20,
    annualizedReturn: 19.2,
    annualizedVol: 16.4,
    beta: 0.62,
    weight: 0,
    color: '#ca8a04',
    currency: '₹'
  },
  {
    id: 'sbin',
    ticker: 'SBIN.NS',
    name: 'State Bank of India',
    category: 'Equities',
    market: 'NSE India',
    price: 845.30,
    change24h: -0.65,
    change24hAmount: -5.50,
    annualizedReturn: 26.4,
    annualizedVol: 27.2,
    beta: 1.28,
    weight: 0,
    color: '#0284c7',
    currency: '₹'
  },
  {
    id: 'larsen',
    ticker: 'LT.NS',
    name: 'Larsen & Toubro Ltd.',
    category: 'Equities',
    market: 'NSE India',
    price: 3620.00,
    change24h: 1.15,
    change24hAmount: 41.20,
    annualizedReturn: 21.8,
    annualizedVol: 20.6,
    beta: 1.05,
    weight: 0,
    color: '#65a30d',
    currency: '₹'
  },
  {
    id: 'trent',
    ticker: 'TRENT.NS',
    name: 'Trent Limited (Zudio / Westside)',
    category: 'Equities',
    market: 'NSE India',
    price: 6850.00,
    change24h: 3.45,
    change24hAmount: 228.60,
    annualizedReturn: 68.4,
    annualizedVol: 34.2,
    beta: 1.35,
    weight: 0,
    color: '#ea580c',
    currency: '₹'
  },
  {
    id: 'tatamotors',
    ticker: 'TATAMOTORS.NS',
    name: 'Tata Motors Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 985.40,
    change24h: 1.65,
    change24hAmount: 16.00,
    annualizedReturn: 32.4,
    annualizedVol: 28.5,
    beta: 1.38,
    weight: 0,
    color: '#2563eb',
    currency: '₹'
  },
  {
    id: 'maruti',
    ticker: 'MARUTI.NS',
    name: 'Maruti Suzuki India',
    category: 'Equities',
    market: 'NSE India',
    price: 12450.00,
    change24h: 0.85,
    change24hAmount: 105.00,
    annualizedReturn: 18.6,
    annualizedVol: 19.8,
    beta: 0.88,
    weight: 0,
    color: '#0891b2',
    currency: '₹'
  },
  {
    id: 'sunpharma',
    ticker: 'SUNPHARMA.NS',
    name: 'Sun Pharmaceutical Ltd.',
    category: 'Equities',
    market: 'NSE India',
    price: 1720.50,
    change24h: 1.25,
    change24hAmount: 21.20,
    annualizedReturn: 22.8,
    annualizedVol: 18.2,
    beta: 0.72,
    weight: 0,
    color: '#059669',
    currency: '₹'
  },
  {
    id: 'titan',
    ticker: 'TITAN.NS',
    name: 'Titan Company Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 3420.00,
    change24h: 0.92,
    change24hAmount: 31.20,
    annualizedReturn: 26.5,
    annualizedVol: 22.4,
    beta: 0.95,
    weight: 0,
    color: '#d97706',
    currency: '₹'
  },
  {
    id: 'bajfinance',
    ticker: 'BAJFINANCE.NS',
    name: 'Bajaj Finance Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 6980.00,
    change24h: 1.45,
    change24hAmount: 99.80,
    annualizedReturn: 28.2,
    annualizedVol: 26.8,
    beta: 1.22,
    weight: 0,
    color: '#7c3aed',
    currency: '₹'
  },
  {
    id: 'hal',
    ticker: 'HAL.NS',
    name: 'Hindustan Aeronautics Ltd.',
    category: 'Equities',
    market: 'NSE India',
    price: 4680.00,
    change24h: 2.45,
    change24hAmount: 112.00,
    annualizedReturn: 52.4,
    annualizedVol: 32.1,
    beta: 1.18,
    weight: 0,
    color: '#dc2626',
    currency: '₹'
  },
  {
    id: 'bel',
    ticker: 'BEL.NS',
    name: 'Bharat Electronics Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 295.40,
    change24h: 1.95,
    change24hAmount: 5.65,
    annualizedReturn: 44.8,
    annualizedVol: 26.4,
    beta: 1.08,
    weight: 0,
    color: '#0d9488',
    currency: '₹'
  },
  {
    id: 'ntpc',
    ticker: 'NTPC.NS',
    name: 'NTPC Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 412.00,
    change24h: 0.65,
    change24hAmount: 2.65,
    annualizedReturn: 24.2,
    annualizedVol: 18.6,
    beta: 0.85,
    weight: 0,
    color: '#b45309',
    currency: '₹'
  },
  {
    id: 'powergrid',
    ticker: 'POWERGRID.NS',
    name: 'Power Grid Corp of India',
    category: 'Equities',
    market: 'NSE India',
    price: 338.50,
    change24h: 0.45,
    change24hAmount: 1.50,
    annualizedReturn: 21.4,
    annualizedVol: 16.2,
    beta: 0.68,
    weight: 0,
    color: '#15803d',
    currency: '₹'
  },
  {
    id: 'tatasteel',
    ticker: 'TATASTEEL.NS',
    name: 'Tata Steel Limited',
    category: 'Equities',
    market: 'NSE India',
    price: 154.20,
    change24h: 1.85,
    change24hAmount: 2.80,
    annualizedReturn: 20.5,
    annualizedVol: 31.4,
    beta: 1.42,
    weight: 0,
    color: '#475569',
    currency: '₹'
  },

  // ==========================================
  // 2. SOVEREIGN G-SEC, PSU TAX-FREE & CORPORATE BONDS
  // ==========================================
  {
    id: 'in10y',
    ticker: 'IN10Y.NS',
    name: 'India 10Y Sovereign G-Sec Bond (7.18% 2033)',
    category: 'Bonds',
    market: 'RBI / NDS-OM Debt',
    price: 101.40,
    change24h: 0.12,
    change24hAmount: 0.12,
    annualizedReturn: 7.18,
    annualizedVol: 4.5,
    beta: -0.28,
    weight: 15,
    color: '#059669',
    currency: '₹'
  },
  {
    id: 'rec_taxfree',
    ticker: 'REC-TF',
    name: 'REC AAA Tax-Free PSU Bond (7.38% Sec 10(15))',
    category: 'Bonds',
    market: 'NSE Debt / PSU',
    price: 104.20,
    change24h: 0.05,
    change24hAmount: 0.05,
    annualizedReturn: 7.38,
    annualizedVol: 3.8,
    beta: -0.22,
    weight: 10,
    color: '#047857',
    currency: '₹'
  },
  {
    id: 'pfc_taxfree',
    ticker: 'PFC-TF',
    name: 'PFC AAA Tax-Free PSU Bond (7.42% Sec 10(15))',
    category: 'Bonds',
    market: 'NSE Debt / PSU',
    price: 104.80,
    change24h: 0.04,
    change24hAmount: 0.04,
    annualizedReturn: 7.42,
    annualizedVol: 3.9,
    beta: -0.20,
    weight: 0,
    color: '#0f766e',
    currency: '₹'
  },
  {
    id: 'nhai_54ec',
    ticker: 'NHAI-54EC',
    name: 'NHAI Capital Gains Exemption Bond (5.25% Sec 54EC)',
    category: 'Bonds',
    market: 'Primary / NHAI Direct',
    price: 100.00,
    change24h: 0.00,
    change24hAmount: 0.00,
    annualizedReturn: 5.25,
    annualizedVol: 0.5,
    beta: -0.05,
    weight: 0,
    color: '#0369a1',
    currency: '₹'
  },
  {
    id: 'irfc_taxfree',
    ticker: 'IRFC-TF',
    name: 'IRFC AAA Tax-Free Railway Bond (7.55% 2030)',
    category: 'Bonds',
    market: 'NSE Debt Market',
    price: 105.10,
    change24h: 0.06,
    change24hAmount: 0.06,
    annualizedReturn: 7.55,
    annualizedVol: 3.7,
    beta: -0.21,
    weight: 0,
    color: '#1d4ed8',
    currency: '₹'
  },
  {
    id: 'hdfc_bond',
    ticker: 'HDFC-AAA',
    name: 'HDFC Bank AAA Corporate NCD Bond (7.85% 2028)',
    category: 'Bonds',
    market: 'NSE Debt Market',
    price: 102.80,
    change24h: 0.08,
    change24hAmount: 0.08,
    annualizedReturn: 7.85,
    annualizedVol: 5.2,
    beta: -0.15,
    weight: 5,
    color: '#0284c7',
    currency: '₹'
  },
  {
    id: 'tata_bond',
    ticker: 'TATA-AAA',
    name: 'Tata Capital AAA Secured NCD (8.15% 2029)',
    category: 'Bonds',
    market: 'NSE Debt Market',
    price: 103.40,
    change24h: 0.10,
    change24hAmount: 0.10,
    annualizedReturn: 8.15,
    annualizedVol: 5.5,
    beta: -0.12,
    weight: 0,
    color: '#3b82f6',
    currency: '₹'
  },
  {
    id: 'shriram_fd',
    ticker: 'SHRIRAM-FD',
    name: 'Shriram Finance Senior Secured NCD (8.80%)',
    category: 'Bonds',
    market: 'BSE Debt / Fixed',
    price: 100.50,
    change24h: 0.02,
    change24hAmount: 0.02,
    annualizedReturn: 8.80,
    annualizedVol: 2.1,
    beta: -0.05,
    weight: 0,
    color: '#9333ea',
    currency: '₹'
  },

  // ==========================================
  // 3. SOVEREIGN GOLD & COMMODITIES (100% INDIAN)
  // ==========================================
  {
    id: 'gold_inr',
    ticker: 'SGB-GOLD.NS',
    name: 'RBI Sovereign Gold Bond (Sec 47(viic) 100% Tax-Free)',
    category: 'Commodities',
    market: 'NSE / RBI Gold',
    price: 7654.20,
    change24h: 0.85,
    change24hAmount: 64.50,
    annualizedReturn: 12.4,
    annualizedVol: 11.8,
    beta: -0.05,
    weight: 15,
    color: '#eab308',
    currency: '₹'
  },
  {
    id: 'goldbees',
    ticker: 'GOLDBEES.NS',
    name: 'Nippon India ETF Gold BeES',
    category: 'Commodities',
    market: 'NSE India',
    price: 64.80,
    change24h: 0.72,
    change24hAmount: 0.46,
    annualizedReturn: 11.8,
    annualizedVol: 12.2,
    beta: -0.04,
    weight: 0,
    color: '#ca8a04',
    currency: '₹'
  },
  {
    id: 'silverbees',
    ticker: 'SILVERBEES.NS',
    name: 'Nippon India ETF Silver BeES',
    category: 'Commodities',
    market: 'NSE India',
    price: 88.50,
    change24h: 1.45,
    change24hAmount: 1.26,
    annualizedReturn: 14.5,
    annualizedVol: 22.4,
    beta: 0.25,
    weight: 0,
    color: '#94a3b8',
    currency: '₹'
  },

  // ==========================================
  // 4. INDIAN MUTUAL FUNDS & INDEX ETFS
  // ==========================================
  {
    id: 'niftybees',
    ticker: 'NIFTYBEES.NS',
    name: 'Nippon India ETF Nifty 50 BeES',
    category: 'ETFs',
    market: 'NSE India',
    price: 275.60,
    change24h: 0.45,
    change24hAmount: 1.23,
    annualizedReturn: 13.9,
    annualizedVol: 14.8,
    beta: 0.95,
    weight: 10,
    color: '#4f46e5',
    currency: '₹'
  },
  {
    id: 'juniorbees',
    ticker: 'JUNIORBEES.NS',
    name: 'Nippon India ETF Nifty Next 50',
    category: 'ETFs',
    market: 'NSE India',
    price: 682.40,
    change24h: 0.85,
    change24hAmount: 5.75,
    annualizedReturn: 17.8,
    annualizedVol: 18.2,
    beta: 1.12,
    weight: 0,
    color: '#7c3aed',
    currency: '₹'
  },
  {
    id: 'bankbees',
    ticker: 'BANKBEES.NS',
    name: 'Nippon India ETF Nifty Bank',
    category: 'ETFs',
    market: 'NSE India',
    price: 524.80,
    change24h: 1.05,
    change24hAmount: 5.45,
    annualizedReturn: 16.2,
    annualizedVol: 19.5,
    beta: 1.08,
    weight: 0,
    color: '#2563eb',
    currency: '₹'
  },
  {
    id: 'flexi_mf',
    ticker: 'PPFAS.MF',
    name: 'Parag Parikh Flexi Cap Mutual Fund',
    category: 'ETFs',
    market: 'Indian Mutual Funds',
    price: 78.40,
    change24h: 0.65,
    change24hAmount: 0.51,
    annualizedReturn: 18.5,
    annualizedVol: 15.2,
    beta: 0.88,
    weight: 5,
    color: '#059669',
    currency: '₹'
  },
  {
    id: 'mirae_elss',
    ticker: 'MIRAE-ELSS',
    name: 'Mirae Asset ELSS Tax Saver Fund (Sec 80C)',
    category: 'ETFs',
    market: 'Indian Mutual Funds',
    price: 42.80,
    change24h: 0.55,
    change24hAmount: 0.23,
    annualizedReturn: 18.9,
    annualizedVol: 16.4,
    beta: 0.92,
    weight: 0,
    color: '#16a34a',
    currency: '₹'
  }
];

export interface HistoricalDataPoint {
  date: string;
  [ticker: string]: number | string;
}

export function generateHistoricalPrices(): HistoricalDataPoint[] {
  const startDate = new Date(2018, 0, 1);
  const endDate = new Date(2026, 7, 1);
  const points: HistoricalDataPoint[] = [];

  const basePrices: Record<string, number> = {
    'HDFCBANK.NS': 650.00,
    'RELIANCE.NS': 920.00,
    'ICICIBANK.NS': 310.00,
    'TCS.NS': 1850.00,
    'INFY.NS': 600.00,
    'BHARTIARTL.NS': 480.00,
    'ITC.NS': 260.00,
    'SBIN.NS': 310.00,
    'LT.NS': 1250.00,
    'TRENT.NS': 340.00,
    'TATAMOTORS.NS': 240.00,
    'MARUTI.NS': 7200.00,
    'SUNPHARMA.NS': 540.00,
    'TITAN.NS': 850.00,
    'BAJFINANCE.NS': 1800.00,
    'HAL.NS': 820.00,
    'BEL.NS': 68.00,
    'NTPC.NS': 160.00,
    'POWERGRID.NS': 180.00,
    'TATASTEEL.NS': 52.00,
    'IN10Y.NS': 98.50,
    'REC-TF': 100.00,
    'PFC-TF': 100.00,
    'NHAI-54EC': 100.00,
    'IRFC-TF': 100.00,
    'HDFC-AAA': 100.20,
    'TATA-AAA': 100.00,
    'SHRIRAM-FD': 100.00,
    'SGB-GOLD.NS': 3100.00,
    'GOLDBEES.NS': 28.50,
    'SILVERBEES.NS': 38.00,
    'NIFTYBEES.NS': 105.00,
    'JUNIORBEES.NS': 280.00,
    'BANKBEES.NS': 260.00,
    'PPFAS.MF': 24.50,
    'MIRAE-ELSS': 15.20,
    'NIFTY50': 10400.00
  };

  const annualDrifts: Record<string, number> = {
    'HDFCBANK.NS': 0.168,
    'RELIANCE.NS': 0.182,
    'ICICIBANK.NS': 0.245,
    'TCS.NS': 0.174,
    'INFY.NS': 0.165,
    'BHARTIARTL.NS': 0.286,
    'ITC.NS': 0.192,
    'SBIN.NS': 0.264,
    'LT.NS': 0.218,
    'TRENT.NS': 0.684,
    'TATAMOTORS.NS': 0.324,
    'MARUTI.NS': 0.186,
    'SUNPHARMA.NS': 0.228,
    'TITAN.NS': 0.265,
    'BAJFINANCE.NS': 0.282,
    'HAL.NS': 0.524,
    'BEL.NS': 0.448,
    'NTPC.NS': 0.242,
    'POWERGRID.NS': 0.214,
    'TATASTEEL.NS': 0.205,
    'IN10Y.NS': 0.0718,
    'REC-TF': 0.0738,
    'PFC-TF': 0.0742,
    'NHAI-54EC': 0.0525,
    'IRFC-TF': 0.0755,
    'HDFC-AAA': 0.0785,
    'TATA-AAA': 0.0815,
    'SHRIRAM-FD': 0.0880,
    'SGB-GOLD.NS': 0.124,
    'GOLDBEES.NS': 0.118,
    'SILVERBEES.NS': 0.145,
    'NIFTYBEES.NS': 0.139,
    'JUNIORBEES.NS': 0.178,
    'BANKBEES.NS': 0.162,
    'PPFAS.MF': 0.185,
    'MIRAE-ELSS': 0.189,
    'NIFTY50': 0.14
  };

  const dailyVols: Record<string, number> = {
    'HDFCBANK.NS': 0.011,
    'RELIANCE.NS': 0.014,
    'ICICIBANK.NS': 0.014,
    'TCS.NS': 0.011,
    'INFY.NS': 0.013,
    'BHARTIARTL.NS': 0.014,
    'ITC.NS': 0.010,
    'SBIN.NS': 0.017,
    'LT.NS': 0.013,
    'TRENT.NS': 0.022,
    'TATAMOTORS.NS': 0.021,
    'MARUTI.NS': 0.014,
    'SUNPHARMA.NS': 0.012,
    'TITAN.NS': 0.015,
    'BAJFINANCE.NS': 0.018,
    'HAL.NS': 0.020,
    'BEL.NS': 0.017,
    'NTPC.NS': 0.012,
    'POWERGRID.NS': 0.010,
    'TATASTEEL.NS': 0.021,
    'IN10Y.NS': 0.0028,
    'REC-TF': 0.0024,
    'PFC-TF': 0.0025,
    'NHAI-54EC': 0.0005,
    'IRFC-TF': 0.0024,
    'HDFC-AAA': 0.0032,
    'TATA-AAA': 0.0034,
    'SHRIRAM-FD': 0.0015,
    'SGB-GOLD.NS': 0.0078,
    'GOLDBEES.NS': 0.0080,
    'SILVERBEES.NS': 0.0145,
    'NIFTYBEES.NS': 0.009,
    'JUNIORBEES.NS': 0.0115,
    'BANKBEES.NS': 0.0125,
    'PPFAS.MF': 0.0095,
    'MIRAE-ELSS': 0.0105,
    'NIFTY50': 0.0093
  };

  const currentPrices = { ...basePrices };
  let currDate = new Date(startDate);

  function randomNormal() {
    let u = 0, v = 0;
    while(u === 0) u = Math.random();
    while(v === 0) v = Math.random();
    return Math.sqrt( -2.0 * Math.log( u ) ) * Math.cos( 2.0 * Math.PI * v );
  }

  while (currDate <= endDate) {
    const dayOfWeek = currDate.getDay();
    if (dayOfWeek !== 0 && dayOfWeek !== 6) {
      const dateStr = currDate.toISOString().split('T')[0];
      const point: HistoricalDataPoint = { date: dateStr };

      Object.keys(currentPrices).forEach(ticker => {
        const mu = (annualDrifts[ticker] || 0.1) / 252;
        const sigma = (dailyVols[ticker] || 0.015);
        
        const shock = randomNormal() * sigma;
        const returnT = mu + shock;
        currentPrices[ticker] = Math.max(0.001, currentPrices[ticker] * (1 + returnT));
        point[ticker] = Number(currentPrices[ticker].toFixed(3));
      });

      points.push(point);
    }
    currDate.setDate(currDate.getDate() + 1);
  }

  return points;
}
